baseURL = "https://testbooks.cs.ksu.edu/cc520"
languageCode = "en-us"
title = "CC 520 Textbook"

# Change the default theme to be use when building the site with Hugo
theme = "ksucs-hugo-theme"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
page = [ "HTML", "Iframeable", "Teleprompter"]
section = [ "HTML", "Iframeable", "Teleprompter"]

[params]
  editURL = "https://gitlab.cs.ksu.edu/cc/520/generic/cc520-textbook"
  description = "CC 520 Textbook"
  author = "Joshua Weese"
  showVisitedLinks = false
  themeVariant = "purple"
  disableLanguageSwitchingButton = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Custom output format for iframes
[outputFormats]
  [outputFormats.Iframeable]
    name = "Iframeable"
    baseName = "embed"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
  [outputFormats.Teleprompter]
    name = "Teleprompter"
    baseName = "tele"
    mediaType = "text/html"
    isPlainText = false
    isHtml = true
